version: '3'

services:
  gateway:
    extends:
      file: ../gateway/docker-compose.yml
      service: gateway
  issue:
    extends:
      file: ../issue-service/docker-compose.yml
      service: issue-service
  issue-db:
    extends:
      file: ../issue-service/docker-compose.yml
      service: issue-db
  project:
    extends:
      file: ../project-service/docker-compose.yml
      service: project-service
  project-db:
    extends:
      file: ../project-service/docker-compose.yml
      service: project-db
  user:
    extends:
      file: ../user-service/docker-compose.yml
      service: user-service
  user-db:
    extends:
      file: ../user-service/docker-compose.yml
      service: user-db
  news:
    extends:
      file: ../news-service/docker-compose.yml
      service: news-service
  news-mongo:
    extends:
      file: ../news-service/docker-compose.yml
      service: news-mongo
  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    environment:
      - "TZ=Europe/Berlin"
      - "ACTIVEMQ_OPTS=-Dorg.apache.activemq.SERIALIZABLE_PACKAGES=java.lang,javax.security,java.util,org.apache.activemq,org.fusesource.hawtbuf,com.thoughtworks.xstream.mapper,de.thm.mni.microservices,java.time"
    volumes:
      - "./activemq/activemq.xml:/conf/activemq.xml"
    ports:
      - 61616:61616 # broker (admin:adminactivemq)(amq:amq)
      - 8161:8161   # web    http://boot2docker:8161/admin (admin:admin)
    networks:
      - network
  influx:
    image: influxdb:1.8.6
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=PASSWORD
      - DOCKER_INFLUXDB_INIT_ORG=GRUPPE6
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=pqBqD3OIhkdDpbsw8-BrdZ3aqqmkxHKIU6qbTEqGEdSP5iauraGicZoR2Mpd0p8FYyNUqNTTYCnXW5XQU-4YDg==
      - DOCKER_INFLUXDB_INIT_MODE=setup
    ports:
      - 8086:8086
    volumes:
      - ./../influxDB:/var/lib/influxdb
      - ./influx/influx.conf:/etc/influxdb/influx.conf
    networks:
      - network

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/lib:/var/lib/grafana
    networks:
      - network

networks:
  network:
    driver: bridge
  issue-database:
    driver: bridge
  project-database:
    driver: bridge
  user-database:
    driver: bridge
  news-database:
    driver: bridge
