{
 "title": "Microservices-Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "dt_source", "label": "Datasource", "query": "influxdb" }
  ]
 },
 "panels": [
  { "title": "Overview of $dt_source", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "dt_source" },
  {
   "title": "System CPU Usage",
   "type": "gauge",
   "description": "90% Percentille over last 24h ",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" }
     ],
     "measurement": "system_cpu_usage",
     "query": "SELECT percentile(\"cpuUtil\", 90) FROM \"rp_days_14\".\"cpuram\" WHERE $timeFilter GROUP BY time(24h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "gauge",
   "description": "90% Percentille over last 24h ",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" }
     ],
     "measurement": "process_cpu_usage",
     "query": "SELECT percentile(\"cpuUtil\", 90) FROM \"rp_days_14\".\"cpuram\" WHERE $timeFilter GROUP BY time(24h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request-Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Mean",
     "measurement": "http_server_requests",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Upper",
     "measurement": "http_server_requests",
     "select": [
      [
       { "params": [ "upper" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP-Request Status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_outcome",
     "groupBy": [
      { "params": [ "outcome" ], "type": "tag" }
     ],
     "measurement": "http_server_requests",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "$tag_exception",
     "groupBy": [
      { "params": [ "exception" ], "type": "tag" }
     ],
     "measurement": "http_server_requests",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "exception", "operator": "!=", "value": "None" }
     ]
    }
   ]
  },
  {
   "title": "System CPU-Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "CPU-Usage",
     "measurement": "system_cpu_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 4, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "State: $tag_state",
     "groupBy": [
      { "params": [ "state" ], "type": "tag" }
     ],
     "measurement": "jvm_threads_states",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "JVM memory usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 4, "x": 13, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Area: $tag_area, ID: $tag_id",
     "groupBy": [
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "area" ], "type": "tag" }
     ],
     "measurement": "jvm_memory_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Logback-Events",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 4, "x": 17, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Logback-Events: $tag_level",
     "groupBy": [
      { "params": [ "level" ], "type": "tag" }
     ],
     "measurement": "logback_events",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Process Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "process_uptime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Process CPU-Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "measurement": "process_cpu_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Process Start Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "process_start_time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}